### ISSUE TITLE
TLG would not open

### ISSUE THREAD

**Issue by GMKantor** [pjheslin/diogenes#103]
Just reinstalled Diogenes (version 4.6.2) after changing computer and having to move from Windows 10 to Windows 11, and TLG database is no longer opening - when I try to get to the author list or search for an author, it just shows a blank screen. All other databases open fine, including access to TLL and OLD. Any advice much appreciated!

**Comment by pjheslin** [comment]
Duplicate of issue #108. I'll release a new version with the fix soon.
