### ISSUE TITLE
Can't save results [export them]

### ISSUE THREAD

**Issue by carvalhar** [pjheslin/diogenes#15]
Previous version had an option to export a html file, and I couldn't find this option in this version. 
It would be nice to have a pdf export option.

**Comment by pjheslin** [comment]
I made a quick attempt to implement save-file and print-to-PDF menu items in Electron, but I ran into problems in my initial efforts.  I will try again at some point.

Until then, select all and copy and paste into another application.

**Comment by pjheslin** [comment]
This feature (along with print-to-pdf) has been implemented in the latest pre-release (4.0.0pr8).
