### ISSUE TITLE
Morphological search 

### ISSUE THREAD

**Issue by carvalhar** [pjheslin/diogenes#17]
Got a blank page as a result from this search with every word from lemma and flexions
![Capture](https://user-images.githubusercontent.com/20246049/57589701-65340780-74fc-11e9-8b2a-678a042f5744.PNG)
.

**Comment by carvalhar** [comment]
PS: It would be nice to have a catch all to show an error message.

**Comment by pjheslin** [comment]
This works fine for me.  This looks like a result of the other issues you reported with using utf-8 in file names and corpus names.

You will get error messages if you run Diogenes from the command-line.

**Comment by carvalhar** [comment]
In this case there is any utf8

**Comment by pjheslin** [comment]
I cannot reproduce the issue.

![image](https://user-images.githubusercontent.com/9300410/57626136-331eb600-758d-11e9-8aa2-f71fdc1196bc.png)

**Comment by pjheslin** [comment]
OK, thanks -- I have reproduced it.  This bug is an overflow as a result of having selected a very large number of individual forms.

**Comment by pjheslin** [comment]
This should be fixed in the latest pre-release (4.0.0pr8).
