### ISSUE TITLE
Installation and Running Problems (Linux Mint 19.01 )

### ISSUE THREAD

**Issue by oleandrocardoso** [pjheslin/diogenes#19]
Hi, 
I installed the software on my desktop with Linux Mint 19.01 and got the following error report at the end of the installation:

> Selecting previously unselected package diogenes.
(Reading database ... 
(Reading database ... 5%%
(Reading database ... 10%%
(Reading database ... 15%%
(Reading database ... 20%%
(Reading database ... 25%%
(Reading database ... 30%%
(Reading database ... 35%%
(Reading database ... 40%%
(Reading database ... 45%%
(Reading database ... 50%%
(Reading database ... 55%%
(Reading database ... 60%%
(Reading database ... 65%%
(Reading database ... 70%%
(Reading database ... 75%%
(Reading database ... 80%%
(Reading database ... 85%%
(Reading database ... 90%%
(Reading database ... 95%%
(Reading database ... 100%%
(Reading database ... 370897 files and directories currently installed.)
Preparing to unpack .../diogenes-4.0.0pr7_amd64.deb ...
Unpacking diogenes (4.0.0pr7) ...
Setting up diogenes (4.0.0pr7) ...
/var/lib/dpkg/info/diogenes.postinst: 3: /var/lib/dpkg/info/diogenes.postinst: /usr/bin/update-menus: not found
dpkg: error processing package diogenes (--install):
 installed diogenes package post-installation script subprocess returned error exit status 127
Processing triggers for desktop-file-utils (0.23+linuxmint5) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 diogenes

With the program running, when I click on the name of an author to open the list of works, I receive the following message in a dialog box (same thing happens when I click on any link in the program):

![Captura de tela de 2019-05-27 13-51-05](https://user-images.githubusercontent.com/51092810/58432751-5ae04480-808a-11e9-9073-34c86ec0cb4d.png)
 
Can someone help me with these problems?
Thank you in advance for your attention.

**Comment by pjheslin** [comment]
Thanks for the report.  The installation problem is already fixed in the repo and will be fixed in the deb file when next pre-release comes out.  At the moment, I am busy finishing the xml-export functionality, so apologies for the delay in getting that out.  How were you able to run Diogenes if the installer failed?  The javascript error is not something I've seen before.  Is it still happening?

**Comment by oleandrocardoso** [comment]
Hi, thanks for the reply. I also do not know how the program ran after the error reported in the installation: I simply clicked the icon that appeared after the installation and the program opened, but with the javascript error - it's still happening, and after the error message appears, nothing else works in the program until it is restarted. I will wait for the new release to find out if the javascript error is related to the installation failure or if it can be something else. Thanks!

**Comment by Doc73** [comment]
@oleandrocardoso 
Try downloading and compiling the source package, then launch the perl server with this command:

`/PATH-TO-DIOGENES-FORLDER/diogenes-server.pl`

and with browser, point to this page: [http://127.0.0.1:8888](url)

You have the same error wich I had in my Debian Sid, complaining about missing `/usr/bin/update-menus`, but in my PC Diogenes works very well. Therefore, your bug doesn't depend on the error you got during installation.Try in the way I suggested above!

**Comment by oleandrocardoso** [comment]
Hi, @Doc73 !
Thank you for your help. I'll try this until the new version becomes available.

**Comment by pjheslin** [comment]
This should be fixed in the latest pre-release (4.0.0pr8).
