### ISSUE TITLE
Liddell-Scott-Jones not working

### ISSUE THREAD

**Issue by Doc73** [pjheslin/diogenes#2]
I can confirm that [issue#12](https://github.com/nickjwhite/diogenes/issues/12) still persists.

I've already tried to compile the app manually, but at Step 4 it returns an error, which I can't remember: maybe tomorrow I'll try again!

```
server stderr: [Fri Mar 29 22:39:41 2019] diogenes-server.pl: Diogenes Error: No such file or directory at /usr/local/diogenes/server/../dependencies/CPAN/CGI/Carp.pm line 314, <GEN21> line 26.
```

Thanks in advance!

**Comment by pjheslin** [comment]
Please do report the error you get when building.

**Comment by Doc73** [comment]
Yes, tomorrow (I live in Italy and it's time to go to bed :laughing: ) !

In the meantime, these was the steps I did today:

1. I downloaded the latest zip from master branch
2. `make -f mk.prebuilt-data`
3. `make`
4. `make installer-deb64`
5. I installed the resulting deb file

If I understood well the instructions, in this way I obtained Perseus version, isn't it?

I tried the manual compilation yesterday, but with no success!

**Comment by pjheslin** [comment]
Ah!  I forgot to update the prebuilt-data repo after the many recent changes to the code.  I've just updated diogenes-prebuilt-data now, including the Logeion version of LSJ.  Hopefully that will fix it.

**Comment by Doc73** [comment]
Mmmmm.... no! With generic `make -f mk.prebuilt-data` LSJ is still not working.

In some case, it appears "(NB. Could not find dictionary headword; this is around the spot it should appear.)"

In the aftermoon, I'll try step-by-step compilation.

**Comment by pjheslin** [comment]
You're right.  There was an error in mk.prebuilt-data.  Pull my commit and the steps you listed again should work.  I've tested it on my own Debian machine this time, and it works for me.

**Comment by Doc73** [comment]
Beh, it's not necessary: I have a Debian Stretch machine too
