### ISSUE TITLE
Add an option to jump to a stephanus page when reading it

### ISSUE THREAD

**Issue by carvalhar** [pjheslin/diogenes#20]
![Untitled-1](https://user-images.githubusercontent.com/20246049/58501641-415afd80-815b-11e9-8057-a1d306e45751.jpg)

Is it possible to add an option to jump to a stepanhus pagination and not only moving by forward/back when reading?

**Comment by pjheslin** [comment]
This is not a bad idea - I can see that it would be a useful shortcut in some use cases.  I'll add it as a to-do item to see if it's easy to implement, but it is not be a high priority item at the moment.  Thanks for the suggestion.
