### ISSUE TITLE
Wordlist search

### ISSUE THREAD

**Issue by Brauronios** [pjheslin/diogenes#21]
At the risk to seem vexatious, I am compelled to open a new issue.

When I find an item in the TLG wordlist, then select it and give the command "do the search", the result is nothing. Blank page!
Any hints?

**Comment by pjheslin** [comment]
It's not vexatious at all!  It's a great help.  I have confirmed the bug --
one of my recent changes must have broken word-list searching.  I'll look
into it now.

P.

**Comment by pjheslin** [comment]
I have fixed this bug with commit e6be2b7098c6aa62354466f93c4fce9813a2c482 It will be in the next pre-release.  Thanks again for the report!
