### ISSUE TITLE
Inflected Forms error

### ISSUE THREAD

**Issue by caioaguida** [pjheslin/diogenes#22]
Dear Heslin,

I was doing some "intensive" queries today and found an error, which was not seen when using the version 3.2.0. I'm doing queries of inflected forms of δοκέω in the 3rd sg act in Plato, Xenophon and Herodotus and the result screen appears completely blank. After a while, I tried smaller corpora and even working with συνδοκέω or κελευστής in Plato only. The errors are very similar in their ending:

> server stderr: [Mon Aug 19 16:50:07 2019]diogenes-server.pl: Use of uninitialized value in subtraction (-) at /usr/local/diogenes/server/Diogenes/Search.pm line 610.
server stderr: [Mon Aug 19 16:50:07 2019] diogenes-server.pl: Diogenes Error: ERROR: Disappearing Match!!

As for the longer queries, there are some other outputs which I can't be sure if they are related, most of them being "Use of uninitialized value" and some of them like the following:

>server stderr: [Mon Aug 19 16:27:09 2019] diogenes-server.pl: 
[Mon Aug 19 16:27:09 2019] diogenes-server.pl: 
[Mon Aug 19 16:27:09 2019] diogenes-server.pl: #########################################################################
[Mon Aug 19 16:27:09 2019] diogenes-server.pl: ERROR: For the word 'DOCA The total count in the word list is , but I only see 1 in tlgwcnts.inx.
[Mon Aug 19 16:27:09 2019] diogenes-server.pl: 
[Mon Aug 19 16:27:09 2019] diogenes-server.pl: Please send a copy of this error message to the author of the program.
[Mon Aug 19 16:27:09 2019] diogenes-server.pl: Diogenes version (4.0.0pr8).
[Mon Aug 19 16:27:09 2019] diogenes-server.pl: #########################################################################
[Mon Aug 19 16:27:09 2019] diogenes-server.pl: 
[Mon Aug 19 16:27:09 2019] diogenes-server.pl: Use of uninitialized value $current_block in numeric eq (==) at /usr/local/diogenes/server/Diogenes/Indexed.pm line 388.

The version information:
Diogenes version: 4.0.0pr8 
OS: Linux - 4.19.66-1-MANJARO

In time, thanks for the new version!
Best regards,
Caio

**Comment by cborgesg** [comment]
Sorry for the self-answer, but I just checked the log from the 3.2.0 version: the second group of errors above mentioned is also present in the older version, so they may not be related to the main issue. I did a very long morphological search within the whole corpora in 3.2.0 and the software handles it just fine.

**Comment by pjheslin** [comment]
Apologies for not responding to this report earlier -- I have been focussed on getting version 4.0 finished.  If you are still bothered by this bug, send me a more precise recipe to reproduce it.
