### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by mlana** [pjheslin/diogenes#24]
hi peter, 
thank you for updating diogenes so it works will the upcoming OSX Catalina!
i installed it and tried the TLL pdf's download.
the TLL pdfs directory is defined but when in the File menu i click on Download TLL files i get this error (i ocr'ed the error message appearing onscreeen):
_A Javascript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'webContents' of undefined
at click (/Applications/Diogenes.app/Contents/Resources/
app/main.js:422:29)
at MenuItem.click (/Applications/Diogenes.app/Contents/
Resources/electron.asar/browser/api/menu-item.js:56:9)
at Function.executecommand (/App|ications/Diogenes.app/
Contents/Resources/electron.asar/browser/api/menu.js:31:13)_
any idea?
best
maurizio

**Comment by pjheslin** [comment]
How odd.  I've just tried it on my Mac (OS X Mojave), and it works fine.  Are you using version 4.0.0 of Diogenes (as opposed to one of the pre-releases?).  Are you running a beta pre-release of OS X Catalina?  Do other menu items work as expected?

Best,

Peter

**Comment by mlana** [comment]
Il 24/09/19 15:31, pjheslin ha scritto:
    
    
      
      How odd. I've just tried it on my Mac (OS X Mojave), and it
        works fine. Are you using version 4.0.0 of Diogenes (as opposed
        to one of the pre-releases?). Are you running a beta pre-release
        of OS X Catalina? Do other menu items work as expected?
    
    hi peter,
    it happens with diogenes 4.0.0, i am running mojave 10.14.6 - for
    the other menu items i don't know because i must re-set my copies of
    PHI and TLG from CD. i think i will do it tomorrow and will make you
    know
    best
    maurizio
    -- 
In pochi a nuoto arrivammo qui sulle vostre spiagge. 
Ma che razza di uomini è questa? Quale patria permette 
un costume così barbaro, che ci nega perfino l’ospitalità 
della sabbia; che ci dichiara guerra e ci vieta di posarci 
sulla vicina terra. Se non credete nel genere umano e nella 
fraternità tra le braccia mortali, credete almeno negli Dei, 
che ricordano il giusto e l’ingiusto.
[Virgilio, Eneide, Libro I 538-543]
-------
Maurizio Lana

**Comment by JayBrown** [comment]
Fine on 10.14.6.

One little criticism, though. When I selected the folder `TLL/` as the download location, Diogenes adds a subfolder `TLL/tll-pdfs/`, and downloads the PDFs in there, which is not what I told it to do, so I had to move the PDFs up the path afterwards. (But that's just a little thing.)

**Comment by JayBrown** [comment]
Or is that subfolder necessary, because Diogenes will create additional files in the parent folder `TLL/`? Then I would revert the action, of course.

**Comment by JayBrown** [comment]
@mlana : you can always download the PDFs manually, and when you're done, put them in a folder next to PHI/TLG, and direct Diogenes to that folder in the database settings.

**Comment by pjheslin** [comment]
I did that deliberately, so that naive users will not end up with the PDFs
spammed all over their (e.g.) desktop.  I realise that it may be a mild
annoyance for expert users.

Peter

**Comment by mlana** [comment]
Il 24/09/19 15:31, pjheslin ha scritto:
    
    
      
      How odd. I've just tried it on my Mac (OS X Mojave), and it
        works fine. Are you using version 4.0.0 of Diogenes (as opposed
        to one of the pre-releases?). Are you running a beta pre-release
        of OS X Catalina? Do other menu items work as expected?
    
    two times odd, peter, now i retried and everything is working, the
    TLL are slowly arriving in their directory
    the only difference is that i have setuop the direwctories for the
    TLG and PHI files - but i think it's irrelevant.
    anyway the program is working perfectly
    kudos!
    maurizio
    
    -- 
In pochi a nuoto arrivammo qui sulle vostre spiagge. 
Ma che razza di uomini è questa? Quale patria permette 
un costume così barbaro, che ci nega perfino l’ospitalità 
della sabbia; che ci dichiara guerra e ci vieta di posarci 
sulla vicina terra. Se non credete nel genere umano e nella 
fraternità tra le braccia mortali, credete almeno negli Dei, 
che ricordano il giusto e l’ingiusto.
[Virgilio, Eneide, Libro I 538-543]
-------
Maurizio Lana - 347 737 0925

**Comment by pjheslin** [comment]
I'm glad the problem resolved itself!

Peter
