### ISSUE TITLE
Use of diogenes.config file

### ISSUE THREAD

**Issue by aurelberra** [pjheslin/diogenes#26]
I am absolutely delighted to see that this beautiful new version of Diogenes has been released. Congratulations!

I have tried to add a config file in the directory mentioned in the application, but it causes Diogenes to open a blank window. I intended to specify a font for the interface as a value of `cgi_font`. When my config file only contains a copy of the current, i.e. default, settings, it results in the same behaviour. As soon as I remove the config file, everything works like a charm, even without restarting the application.

Tweaking the CSS shows me that I could get the expected result. This is obviously not the best solution.

Although this happens on a Mac with MacOS 10.14.6, I suspect it is just due to my ignorance of the proper syntax for the config file. I could not find any hint or documentation on the main website or on this repository. Any help would be most welcome.

**Comment by Doc73** [comment]
In my Linux system, the config file is `~/.config/Diogenes/diogenes.config`, but the right name il `/home/domenico/.config/Diogenes/diogenes.prefs`.

Try the other name!

**Comment by aurelberra** [comment]
Thanks for the suggestion!

There is no `~/.config/Diogenes/` on MacOS and the "For experts" section of the "Other settings" window states: "You can add these manually to a configuration file: /Users/***/Library/Application Support/Diogenes/diogenes.config" (with the relevant user name).

The `diogenes.prefs` file is created on setup and contains the locations of the databases. It is listed in the second line of the "Diogenes settings" page: `auto_config => '/Users/aurel/Library/Application Support/Diogenes/diogenes.prefs',`.

I tried renaming my file from `.config` to `.prefs` (both copying the current settings page and trying to reformat the lines to match the syntax of the autogenerated `.prefs` file) but I only lost the location of the databases and had to point to them again.

**Comment by Doc73** [comment]
Ah, ok!
I tried creating a `/home/xxxxx/.config/Diogenes/diogenes.config` file and... blank window!

**Comment by aurelberra** [comment]
Good! I mean: bad! But I'm sure some documentation will make things straight. The behaviour of the config file has probably changed.

**Comment by pjheslin** [comment]
diogenes.prefs is a file written by the electron client and should not be edited manually; diogenes.config is for manual editing by the user.  Both are read by Diogenes.

The cgi_font setting is no longer in use in version 4.0.  I should have removed it -- there are probably other settings that also need to be removed,

When you set a value for cgi_font, Diogenes should have ignored it.  My guess is that there was a syntax error in the .config file.  To see those errors, start Diogenes from the command line, which should give you more info when there is a blank page.

**Comment by Doc73** [comment]
This is the error:
```
server stderr: [Wed Sep 25 12:09:05 2019] diogenes-server.pl: Diogenes Error: Configuration file error in parameter: auto_config
```
Removing `auto_config` string solves the issue: Diogenes starts fine, but `cgi_font` string has no effects.

**Comment by pjheslin** [comment]
I'm not sure how auto_config got in there.

As I said, cgi_font should not have any effect now.  Older versions of Diogenes were dependent on whatever Unicode fonts the user had installed.  Version 4.0 comes with Gentium, which is free, elegant, and has much better coverage than any other font I know.  This provides a much better out of the box experience for most users. One of the design goals of Diogenes is to provide a good default experience for the majority of users, who are not technically adept, not to provide maximum configurability for experts. 

If someone hates Gentium for some genuine reason (other than just not liking change), there is no longer any mechanism to change it, as the font now sits on the client side, rather than the server side, where the config file has effect. But the great thing about open source software is that you can just edit the .css file to change the font, as Aurélien discovered.

**Comment by Doc73** [comment]
Gentium is an excellent font and I used it for my book, but in Linux systems there are antiliasing issues with fonts installed in not standard paths, i. e. in Diogenes folder.

But, it is only a cosmethic issue and I can live with it. :smile: 

BTW, many thanks for your efforts in developing this excellent software and for your patience with us!

**Comment by aurelberra** [comment]
Many thanks for the explanation, @pjheslin. Everything is clear now!

**Comment by aurelberra** [comment]
Many thanks for the explanation, @pjheslin. Everything is clear now!

**Comment by pjheslin** [comment]
Subpixel rendering is a Linux system issue, or possibly an Electron issue, so I can only hope that it will be sorted out on that level.  Font rendering in Chrome looks good on Linux, so it should not be a problem for Electron to inherit whatever they have done there.

My own Linux box has an old, low resolution monitor, but I tested Diogenes 4 on a friend's hi-dpi Google pixelbook running Debian, and it looked just as good as on my Macbook with a Retina display.  So I hope all this will be sorted out in time.

P.

**Comment by vcaston** [comment]
Aurélien, could you tell me how you altered the css file? I tried using the name of the font-family to "Minion Pro" and changed the two @font-face directions to the path for the italic and regular Minion Pro OTF fonts I'd placed in the folder, but with no success.

Many thanks!

Victor

**Comment by aurelberra** [comment]
Hi Victor. My answer will come as a disappointment. I had been able to change the font in the CSS directly in the browser window that Diogenes is (opening the “Developer Tools” pane), but I did not have more luck than you in tweaking the Diogenes CSS file itself. It's probably possible and I’m still interested in a solution. However, I love Gentium, one of the open source fonts I regularly recommend, and decided I was satisfied with Peter’s choice and new implementation…

**Comment by Doc73** [comment]
I did some tests with full success!
Here are my settings:
```
body {
  background-color: #ffffff;
  color: #000000;
  font-family: 'Noto Sans';
  font-synthesis: weight;
  height: 100%;
  margin: 0px;
}
...
@font-face {
  font-family: 'Noto Sans';
  src: url('/usr/share/fonts/truetype/noto/NotoSans-Italic.tff');
  font-weight: normal;
  font-style: italic;
}
@font-face {
  font-family: 'Noto Sans';
  src: url('/usr/share/fonts/truetype/noto/NotoSans-Regular.tff');
  font-weight: normal;
  font-style: normal;
}
```

**Comment by vcaston** [comment]
Hmm. So I found the css file here:

/Applications/Diogenes.app/Contents/server/diogenes.css

There's also a fonts folder in the same directory.

**Comment by vcaston** [comment]
Doc73, that's interesting — I used relative addresses, but without success:

@font-face {
  font-family: 'Minion Pro';
  src: url('fonts/MinionPro It.otf');
  font-weight: normal;
  font-style: italic;
}
@font-face {
  font-family: 'Minion Pro';
  src: url('fonts/MinionPro Regular.otf');
  font-weight: normal;
  font-style: normal;
}

**Comment by Doc73** [comment]
@vcaston 
I think that in your case you should use _.woff_ fonts files

**Comment by vcaston** [comment]
All I have are the OTFs

**Comment by Doc73** [comment]
Yes, but I don't think there are woff files of Minion Pro.
Therefore, I think you should use full path to fonts (OTF or TTF).

**Comment by vcaston** [comment]
I see — thanks. Is it important that it's in a 'share' folder?

**Comment by Doc73** [comment]
@vcaston 
I use a Linux System and Noto is a system font. I think that you should use also other paths, but I don't know how Mac OSX works...

**Comment by vcaston** [comment]
Didn't work with the actual folder

**Comment by Doc73** [comment]
:-(

**Comment by aurelberra** [comment]
Here are the working alternatives on MacOS. Note that I only define the regular font here, the italic has to be defined the same way of course. I have tested both TTF and OTF fonts.

```
body {
  font-family: 'Libertinus Serif';
}

/* Pointing to font files in Diogenes `fonts` dir */
@font-face {
  font-family: 'Libertinus Serif';
  src: url('/fonts/LibertinusSerif-Regular.otf');
  font-weight: normal;
  font-style: normal;
}

/* Pointing to font files in usual local dir on your system (use font file name without its extension) */
@font-face {
  font-family: 'Libertinus Serif';
  src: local('LibertinusSerif-Regular');
  font-weight: normal;
  font-style: normal;
}
```

**Comment by pjheslin** [comment]
Thanks for working on this, Aurélien!  I've put a link to this thread in the FAQs.

**Comment by vcaston** [comment]
Many thanks for this, Aurélien — the first version (url) is what I actually had, but didn't work until Philipp Steinkrüger pointed out to me that you need to delete the contents of the cache first:

~/Library/Application Support/Diogenes/Cache/

Perhaps that goes without saying, but I had overlooked it. Thanks, all!

**Comment by pjheslin** [comment]
Dear Gentium haters ;-)

I've just released Version 4.4 of Diogenes, which has a facility for easily changing the display font.  Go to the File menu and click on Change Font.

**Comment by Doc73** [comment]
:smile: 

I composed my book with Gentium, but on screen is terrible!

**Comment by aurelberra** [comment]
Works like a charm! Gentium *and* freedom, that's a treat.
