### ISSUE TITLE
LSJ entry display

### ISSUE THREAD

**Issue by helmadik** [pjheslin/diogenes#28]
This is less an issue than a possible enhancement. The headings for sections within entries of LSJ are only moderately unreliable (Perseus scripts added "A" for the first 'sense' everywhere). Would be nice to display them. But I should hasten to add that Ι already like the display very much, with the indents for the senses and the bold+italic for glosses.

**Comment by pjheslin** [comment]
I have no idea why I left the headings out.  Maybe just inadvertence and then I got used to not seeing them.  I have put the LSJ headings back with commit 7e95a2006176948b398235b3e95c2479106334f0.

It looks much better now, thanks! (Apart from entries like ἐπιγραφή, where the senses wrongly begin with a stray dot left over from the heading.  Aargh).

**Comment by helmadik** [comment]
Hmm, the dots ring a bell but my ἐπιγραφή entry has Roman numerals where
you have dots?

Helma Dik
Department of Classics
University of Chicago

**Comment by helmadik** [comment]
PS:
Minimal sub-issue: Add instruction to user to use Greek characters when
looking things up in LSJ. I just got Latin epigramma:-)

Helma Dik
Department of Classics
University of Chicago

**Comment by pjheslin** [comment]
Good idea -- I've added a hint to use Greek letters to look up a Greek word.

The online Logeion has removed the stray dots, but they are present in the Logeion XML.  Maybe you do some cleaning-up when you convert to HTML.

**Comment by JayBrown** [comment]
Maybe also include links to GreekKeys (which I use, with costs) and the freeware SophoKeys.

https://classicalstudies.org/publications-and-research/about-greekkeys-2015
https://benjaminblonder.org/sophokeys/

**Comment by helmadik** [comment]
I should probably upload the latest files; may have caught this at some
point. Ditto for the morphology.

**Comment by pjheslin** [comment]
Are the Logeion morphology files publicly available?  I looked in the Logeion github and your personal github account and didn't see them.
