### ISSUE TITLE
Could not parse ~ηιτ~... 

### ISSUE THREAD

**Issue by helmadik** [pjheslin/diogenes#29]
Yay for version 4.1! 
This ("Could not parse ~ηιτ~τολμήστατε. Looking in dictionary") when trying to parse the search term within the search results) is an existing bug from earlier versions of Diogenes, I think. I looked up a word for which I'd just added a morphological parse in Logeion, knowing that it wouldn't be parsed in Morpheus. Of course I can look up parse of the word just fine after going to 'context'.

**Comment by pjheslin** [comment]
I couldn't reproduce this.  What exactly was your search term?

**Comment by helmadik** [comment]
search for τολμήστατε
click on that word in the result.

Helma Dik
Department of Classics
University of Chicago

**Comment by pjheslin** [comment]
That's exactly what I did.  I tried again, both a simple search and a word-list search.  As you say, Morpheus cannot parse it, but I did not get that error (in which the word "hit" is amusingly rendered in Greek).

**Comment by helmadik** [comment]
I deleted the entire Diogenes directories (there was an .ini file dating to 2007 or so, won't swear to that extension) in the Application_Support directory, and that did the trick. yay!
