### ISSUE TITLE
Error Debian Sid

### ISSUE THREAD

**Issue by Doc73** [pjheslin/diogenes#3]
After latest update of my Debian Sid, I got this error:
```
Configurazione di diogenes (4.0.0pr3)...
/var/lib/dpkg/info/diogenes.postinst: 3: /var/lib/dpkg/info/diogenes.postinst: /usr/bin/update-menus: not found
dpkg: errore nell'elaborare il pacchetto diogenes (--configure):
 il sottoprocesso installato pacchetto diogenes script post-installation ha restituito lo stato di errore 127
Configurazione di software-properties-gtk (0.96.20.2-2)...
Elaborazione dei trigger per man-db (2.8.5-2)...
Elaborazione dei trigger per dbus (1.12.12-1)...
Elaborazione dei trigger per shared-mime-info (1.10-1)...
Elaborazione dei trigger per desktop-file-utils (0.23-4)...
Elaborazione dei trigger per mime-support (3.62)...
Elaborazione dei trigger per hicolor-icon-theme (0.17-2)...
Elaborazione dei trigger per gnome-menus (3.32.0-1)...
Elaborazione dei trigger per libc-bin (2.28-8)...
Elaborazione dei trigger per systemd (241-2)...
Elaborazione dei trigger per initramfs-tools (0.133)...
update-initramfs: Generating /boot/initrd.img-4.19.0-4-amd64
Si sono verificati degli errori nell'elaborazione:
 diogenes
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The update involved these packages:
 ```
  apparmor libapparmor1 libinput-bin libinput10 libldb1 libperl5.28
  libsmbclient libuninameslist1 libwbclient0 perl perl-base perl-modules-5.28
  python-sip python3-software-properties samba-libs software-properties-common
  software-properties-gtk thin-provisioning-tools xserver-xorg-input-libinput
```
EDIT (01/04/2017)
Same issue with today update (only package `libgsm1`)

**Comment by pjheslin** [comment]
I've tested the .deb package for release 4.0.0pr6 on my Debian stretch machine and I don't get this error.  According to https://packages.debian.org/sid/amd64/menu/filelist, the file /usr/bin/update-menus is still included in the menu package in Debian sid.  So this error is puzzling. 

It may be that running update-menus is superfluous and that this is done automatically by a post-install trigger.  But I'm not sure.  Does this error prevent the .deb from installing?

**Comment by Doc73** [comment]
In another my machine, with Stretch, I have no issues at all. In the Sid machine, on the contrary, the _deb_ files install itself and the app is working, but I receive that error both after installing and after every system upgrade.

To avoid this annoying warning, I compiled the binary and put the folder by hand in `/usr/local/`.

Later, I can try the latest deb file.

**Comment by pjheslin** [comment]
Could you check if you the "menu" package has been installed on your Sid machine?  With something like sudo dpkg -l | grep menu

**Comment by pjheslin** [comment]
The latest .deb file is here:
https://github.com/pjheslin/diogenes/releases/download/4.0.0pr6/diogenes-4.0.0pr6_amd64.deb

**Comment by Doc73** [comment]
`menu` package isn't installed in my Sid!

Perhaps it is no longer necessary, and indeed in the repos there is a version identical to that of Stretch and it seems unmantained!

https://tracker.debian.org/pkg/menu

**Comment by pjheslin** [comment]
That's strange (unless your Sid box is a server that does not get used with a graphical desktop).  Removing the menu package would be a major change of Debian policy, and I don't see any indication of that.  Maybe it's just a bug in the dependencies of one of the desktop environment packages in Sid.  Can I ask what desktop you use on that machine?

**Comment by Doc73** [comment]
Stock Gnome 3.30

**Comment by pjheslin** [comment]
I've changed the script to test for the existence of the update-menus command, which should eliminate the error.  What I'm not sure of is whether the menus will get updated without it, by means of a post-install trigger.

**Comment by Doc73** [comment]
Maybe tomorrow I will turn on the pc with SID and test it.
For now, i can tell you that my home server, with Stretch+LXDE, has not installed the `menu` package by default.
In any case, I think I remember that the package in question is generally optional and requested by some WM like `twm`
