### ISSUE TITLE
Re-using pop-up window

### ISSUE THREAD

**Issue by Bipodos** [pjheslin/diogenes#32]
Hello!,
In old Diogenes, I relied very much on the behaviour of pop-up windows. Opening reading Data in a separate window resulted, on first click, in a new window. On second click, the content of that separate window was refreshed. Now, a new window is open. The old behaviour made it possible to keep the analysis window on a separate screen, or behind the text. When testing the pre-release version, I could not make Diogenes work as a stand-alone app (on Mac Mojave), but if running as a server, I could use the windows the old way. 
Could you restore this behaviour to current version?
Using the option "Show in new page" does not help, because Perseus data is open (Mac Mojave) in the same window, as a new page, but there is no "Go back" button.

**Comment by pjheslin** [comment]
Apologies for the slow response.  In version 4 of Diogenes I removed the option to open the morphological and dictionary info in a new window.  It was too difficult to refactor the code for the new version and keep that functionality while making it bug-free.  I'm sorry that this removed something that you found useful, but I think the vast majority of users did not use Diogenes this way.

The new code is improved, however, in a number of regards.  It used to be the case that when you jumped from a lexicon entry to the source of a particular citation, the lexicon entry disappeared from the sidebar, but that is no longer the case, which fixed a problem which for me was one of the main reasons for having the option of opening the lexicon in a new window.
