### ISSUE TITLE
Go back button

### ISSUE THREAD

**Issue by Bipodos** [pjheslin/diogenes#33]
Hello once more,
I am putting this as a separate issue: There is not "go back"  and "Go forward" button in Perseus data in new Diogenes. There are, actually, commands for "Back" and "Forward", accompanied by keyboard shortcuts, but visible buttons, like in text windows, would be very useful.

**Comment by pjheslin** [comment]
The Perseus data panels do not function in the same way as the text panels.  Every time you load a new page of text, you are loading a new web page with a full history available. But the Perseus data is loaded as an addition to the existing page, so it does not come with a  separate history, and it is not possible to have separate back and forward buttons for it.
