### ISSUE TITLE
diogenes-cli doesn't seem to work

### ISSUE THREAD

**Issue by daphniz** [pjheslin/diogenes#37]
Great that you're working on this again!  But with an up-to-date Arch Linux I get

	% ./diogenes-cli.pl
	Can't locate Diogenes/Base.pm in @INC (you may need to install the Diogenes::Base module) (@INC contains: /usr/lib/perl5/5.30/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.30/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.30/core_perl /usr/share/perl5/core_perl) at ./diogenes-cli.pl line 31.
	BEGIN failed--compilation aborted at ./diogenes-cli.pl line 31.

**Comment by daphniz** [comment]
I used to be able to run `perlbrew exec --with 5.10.1
./diogenes-cli.pl`, but not that fails too, even with the old version of
Diogenes.

**Comment by pjheslin** [comment]
It works for me, provided that I run diogenes-cli.pl from the server directory.  It appears that this is what you are doing, so I don't know why this is not working.  How did you install Diogenes?

**Comment by daphniz** [comment]
That's odd.  I installed the Arch package.  But, if I remember
correctly, it used to be possible to run diogenes-cli even before
installing.  I'm using Perl 5.30.1.

**Comment by daphniz** [comment]
Apparently, it's (for security reasons) not considered good practice to
rely on the current directory being included in `@INC`.

https://stackoverflow.com/questions/46549671/doesnt-perl-include-current-directory-in-inc-by-default

**Comment by daphniz** [comment]
And it's not possible from 5.26, so this may be my problem.

**Comment by daphniz** [comment]
https://metacpan.org/pod/release/XSAWYERX/perl-5.26.0/pod/perldelta.pod#Removal-of-the-current-directory-(%22.%22)-from-@INC

**Comment by pjheslin** [comment]
That must be the problem.  Thanks for tracking in down.  I'll have to add the current directory back into quite a few scripts.

**Comment by pjheslin** [comment]
This should be fixed in version 4.3 of Diogenes, though my version of Perl is not advanced enough to test the fix easily.  Please re-open if it's not fixed.
