### ISSUE TITLE
EMACS interface

### ISSUE THREAD

**Issue by daphniz** [pjheslin/diogenes#38]
An EMACS interface would be nice.

**Comment by Doc73** [comment]
I use some shortcuts for emacs.
```
(define-abbrev-table 'global-abbrev-table
  '(
    ("afootnote" "\\edtext{}{\\Afootnote{{\\textbf{\\pstartref{itm:}}}\\enspace}}%" nil 0)
    ("bfootnote" "\\edtext{}{\\Bfootnote{{\\textbf{\\pstartref{itm:}}}\\enspace}}%" nil 0)
    ("grnumber" "\\greeknumeral{}" nil 0)
    ("nrlectio" "\\edtext{}{\\lemma{\\textbf{\\pstartref{itm:}}}\\Cfootnote[nonum,nosep]{}}" nil 0)
    ("pstart" "\\pstart\\edlabel{itm:} \\pend" nil 0)
    ("pstartref" "\\pstartref{itm:}" nil 0)
    ("sidenote" "\\ledsidenote{}" nil 0)
    ("tsuper" "\\textsuperscript{}" nil 0)
    ("vlectio" "\\edtext{}{\\Cfootnote[]{}}" nil 0)
    ("ascii" "\\textascii{}" nil 0)
   ))
```

**Comment by daphniz** [comment]
Sorry, I meant it would be nice to have an EMACS interface for browsing
and looking up, as an alternative to the web interface.

**Comment by Doc73** [comment]
Sorry! And I thought it was a post on the ledmac page! :laughing:

**Comment by pjheslin** [comment]
I use Emacs myself, but the potential user base in the intersection of Emacs users and classicists is not large enough for me to consider it worth investing the effort in creating and maintaining yet another interface.  And there are significant limitations to the Emacs display engine that make it a highly suboptimal solution for rendering text with complex formatting.

**Comment by nitardus** [comment]
A while ago, I wrote some elisp functions to use the diogenes CLI from within emacs. It is a bit rude, but does the job. I've uploaded it to [github](https://github.com/nitardus/diogenes.el). When using it, please make sure to patch the bug in diogenes-cli.pl, or use my [fork](https://github.com/nitardus/diogenes) of diogenes.
