### ISSUE TITLE
Command-line interface

### ISSUE THREAD

**Issue by daphniz** [pjheslin/diogenes#39]
I would also encourage making more powerful command-line tools.  It
would be wonderful to be able, for example, to print an entire work to
STDOUT, or an arbitrary range of lines.

**Comment by pjheslin** [comment]
I do not anticipate having time to add new features to the command-line interface.  You can export an entire work to XML at the command line by using the newly written tool xml-export.pl.  You can then extract an arbitrary range of text from the XML using XPath.
