### ISSUE TITLE
Can no longer look up forms by shell script and server

### ISSUE THREAD

**Issue by daphniz** [pjheslin/diogenes#40]
When I look up an inflexion by directing my browser to the new
diogenes-server, the URL showing is simply

	http://localhost:4107/#
  
It used to be something repeatable, and this allowed me to look
up forms through a shell script

	#!/bin/sh
	curl -s "http://localhost:4107/Diogenes.cgi?JumpTo=&FontName=&action=parse&corpus=TLG+Texts&query=$1&go=Go&current_pageXXstate=splash&greek_output_formatXXstate=UTF-8" \
		| html2text \
		| sed '3,/^All data is (C) the /!d' | head -n -8 \
		| sed '/^Previous Entry/,+3d'

  Would it be feasible to revert to the old behaviour?

**Comment by daphniz** [comment]
Alternatively, if you know of a way to convert the complete
dictionary files into a human-readable (and more easily
script-readable) format, please advise.

**Comment by pjheslin** [comment]
Sorry for the slow response.  The only thing removed was the ability to pop up the parsing information in a new window, but you don't need that.  The API for the Perseus parsing has not changed.  You should do something like this:

curl -s "http://127.0.0.1:8888/Perseus.cgi?do=parse&lang=grk&q=%2A%29/andra"

**Comment by daphniz** [comment]
Thanks!  The cgi changed from `Diogenes.cgi` to `Perseus.cgi`, which
I now see I could have seen by looking in `server/`.

**Comment by pjheslin** [comment]
No, it hasn't changed; it was always called Perseus.cgi.  Your previous script invoked the main cgi script with the Perseus data as its only component, which no longer works.  But calling Perseus.cgi directly was always the more correct option.

**Comment by daphniz** [comment]
But the arrow links to the previous and next entries don't work.

**Comment by pjheslin** [comment]
Apologies -- I misunderstood the problem when you mentioned this.  I should have pointed out that if you add the parameter popup=1 to the query string, the arrow links will work.  Like this:

http://127.0.0.1:8888/Perseus.cgi?do=parse&lang=grk&q=%2A%29/andra&popup=1

**Comment by daphniz** [comment]
Thanks!
