### ISSUE TITLE
png2icns failure

### ISSUE THREAD

**Issue by kesinger** [pjheslin/diogenes#42]
On OSX, commit d0e2ee2f762ed94ea26be906656446ac8488649b (top of master), make attempts to run :

    png2icns build/diogenes.icns build/icons/256.png build/icons/128.png build/icons/48.png build/icons/32.png build/icons/16.png

This fails with 

    Warning: build/diogenes.icns not a valid file - skipping

It looks as if at some point the png2icns api changed? I was able to manually build with 

    png2icns build/icons/256.png  -o build/diogenes.icns -s 16,32,48,256

**Comment by pjheslin** [comment]
Thanks for the report.  I just tested the makefile and it works fine on my OS X machine.  This is with the current version of libicns, which is 0.8.1_3, installed via homebrew.

Are you getting png2icns from a different source than homebrew libicns?

**Comment by kesinger** [comment]
Ah ok, I had installed a npm png2icns, and hadn't read the bit about homebrew libicns in "Building the installers" because I was trying to build standalone.  So this is in the category of 'user error'.

Thanks!

**Comment by pjheslin** [comment]
No: that was my fault. I've fixed the Readme to point out that the icon manipulation packages need to be installed before building the application(s) rather than before building the installer(s).  Thanks for the feedback!
