### ISSUE TITLE
deprecated unicode and other characters

### ISSUE THREAD

**Issue by helmadik** [pjheslin/diogenes#43]
more of a query than an issue: 
I noticed by chance that Greek question marks are encoded with the 037E character, rather than the semicolon. Are there other examples of so-called deprecated unicode?  I have typically followed TLG's overview at http://www.tlg.uci.edu/encoding/quickbeta.pdf which states on page 4, for the semicolon, 
 As of Unicode 4.0 “this, and not 037E ; , is the preferred character for ‘Greek question mark’” (Unicode Standard 5.0, p. 4)."

**Comment by pjheslin** [comment]
Thanks for noticing this.  I implemented Unicode output at a very early stage in the development of the standard and have not attempted to make sure things are up to date.  The current standard (v. 12) says:

> ... use of U+037E and U+0387 ... is not generally encouraged for representation of Greek punctuation.

So they are not exactly deprecated, but I will change them nevertheless.

**Comment by pjheslin** [comment]
Fixed in commit d1ff69bc0105002a20b7eb2602f728a3f5521b74
