### ISSUE TITLE
Dark mode for Diogenes?

### ISSUE THREAD

**Issue by bcdavasconcelos** [pjheslin/diogenes#44]
Is there any interest in making available a dark mode option for Diogenes?
I adapted the original CSS and have been enjoying the result so far.

Here is a screen cap:
![](https://miro.medium.com/max/6720/1*Eh6XiikPsoxWwho48dtpzA.png)
Note: The font here is EB Garamond, but I switched it to Gentium Plus.

**Comment by pjheslin** [comment]
Some people might like that look.  Note that dark mode is a pretty Mac-specific concept at the moment and Diogenes runs on other platforms.  The bigger problem is that at the moment there is no user-friendly mechanism to specify changes to the CSS file. I do need to introduce some mechanism to permit users to vary the CSS, but I'm not sure what the best way to do that will be.

Why don't you paste your CSS changes here and then others can borrow them if they prefer?

**Comment by pjheslin** [comment]
Thanks!  I know that there are many people who want to change the font, so I will think about a way to make the CSS user-configurable, which would make it easier for people to change to dark mode
