### ISSUE TITLE
Diogenes app used in Web Browser

### ISSUE THREAD

**Issue by Doc73** [pjheslin/diogenes#46]
Dear @pjheslin ,
this is not a bug report, but a suggestion for future improvements.

For a long time, I often prefer to use Diogenes directly within a generic browser in my Debian Gnu/Linux system.

This is a short howto, perhaps more aimed at github readers.

**1) Script for Diogenes server**
I use this very simple bash script, that alternatively launches or stops the server:

```
#!/bin/bash

if pidof perl | grep [0-9] > /dev/null

then
	kill -9 `pidof perl`
else
	/usr/local/diogenes/server/diogenes-server.pl & 
fi
```
The file is named `/usr/local/bin/diogenes-server`. Make executable this script by:

`chomd +x /usr/local/bin/diogenes-server`

**2) Launching Diogenes server**
The previous script is called by the following launcher (`/usr/share/applications/diogenes-server.desktop`):
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Encoding=UTF-8
Name=Diogenes server
TryExec=diogenes-server
Exec=diogenes-server
Terminal=false
Type=Application
StartupNotify=true
Icon=diogenes
Categories=Application;Education;Teaching;
```
**3) Using Diogenes**
As you write in yout FAQs, it is sufficient that we browse the site [http://127.0.0.1:8888](http://127.0.0.1:8888).

I hope these simple informations can be useful to someone.

P. S.: many thanks for adding me to your mail-list and for your very precious (and nice) web app.

**Comment by thomasaschmitz** [comment]
Hi Peter, I would like to add one thing: I also prefer using diogenes in a web browser. The settings page (necessary for setting up the location of the databases) can still be reached by adding "Settings.cgi" in the address bar, but there is no obvious way to get to this page. Could the link to it be reestablished (it used to sit at the bottom of the home page)?

**Comment by pjheslin** [comment]
Diogenes was originally intended to be accessed via a web browser.  Version 1 included three scripts that started the server and then opened the browser, in bash, Applescript, and batch file for Linux, Mac and Windows, respectively.  I never intended to create an integrated application, but the fact is that non-technical users found the concept of a separate server and client too hard to understand.  It led to constant frustration for those users who could not understand what to do when something went wrong.  

The vast majority of Diogenes' users are not the kind of people you find discussing issues on Github -- they have a very poor understanding of how computers work, and that I why I have spent so much effort in creating a seamless application that disguises the distinction between client and server.  The average Diogenes user is my main priority.

I removed the link to Settings.cgi to avoid confusing the less technically adept users.  Now there is a menu item in the integrated client that pops up a nice file-picker dialog box.  This is much less error-prone for the average user.  If you want to use a web browser, you have several choices.  You can run the integrated application once, set the database locations there, and then switch to the web browser.  Or you can set the locations by editing the config file manually.  Or type Settings.cgi into the address bar.

I might add a menu item to run Settings.cgi with a warning that it is for experts.
