### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by pgcounillon** [pjheslin/diogenes#48]
Thank you very much for the new Version of Diogenes, compatible with the new Catalina Mac OS (ouf!).
It is very convenient but on one point : It does'nt seem possibe  to cross anymore "word-list "search  (TLG is the only option) and search on a self defined corpus. Or did I miss something? 
Thank you very much
P. Counillon

**Comment by pjheslin** [comment]
You are right.  I accidentally removed the ability to do a TLG word search on a user-defined subset of the TLG.  That was not intentional, and I have put it on my to-do list to reinstate that functionality.

**Comment by pgcounillon** [comment]
Thank you for your answer. I’ll quietly wait.
Sincerely yours,
P. Counillon

**Comment by pjheslin** [comment]
I have just released version 4.4, which fixes this bug.  Thanks for the report!

**Comment by pgcounillon** [comment]
Thank you, it works very well indeed,
Best
P. Counillon
