### ISSUE TITLE
Problem with hovering search bar

### ISSUE THREAD

**Issue by aconser** [pjheslin/diogenes#49]
When I use ⌘F to search the browser, it brings up a hovering search bar. I can type text into it, but nothing happens when I hit 'return'.  Also, when I click the 'X', the hovering bar doesn't disappear.

This is running Diogenes Desktop, version 4.0.0, on a 2017 Macbook Air with High Sierra 10.13.6.

**Comment by pjheslin** [comment]
I believe this bug was fixed in version 4.1 (see the Changes file).  Please upgrade to the current version 4.3 and let me know if the problem persists.
