### ISSUE TITLE
Morphological Search / Inflected Forms

### ISSUE THREAD

**Issue by Bipodos** [pjheslin/diogenes#50]
The functionality stopped working for me in 4.3. I re-downloaded 4.2, and the function works. I am using Mac, and am still on Mojave (due to legacy software and slow work of 64-bit version of EndNote).

**Comment by pjheslin** [comment]
Thanks for the report and sorry for not responding sooner.  I've just released version 4.4, which fixes this bug, introduced in 4.3.
