### ISSUE TITLE
Typos in Perseus L-S xml

### ISSUE THREAD

**Issue by mingshey** [pjheslin/diogenes#53]
This is not actually a Diogenes issue. It is in fact a "Perseus Digital Library" issue. But PDL does not seem to offer an error reporting feature.

The Perseus L-S ("dependencies/data/lat.ls.perseus-eng1.xml") contains some typos.
For example, the entry "oryza" has ὄπνζα as the etymological reference and it is obviously a typo of ὄρυζα. I suspect more typos in the xml and possibly in grc.lsj.xml, too.
I can edit a couple of such typos on the fly for my own use and satisfaction, but if it is to benefit others it would be desirable to have a web based error-reporting-and-correcting system that works like version control systems.
It should be really on the PDL to work far more effectively, but if we can collect considerable amount of errata we could feed it back to PDL. as well.
If there's such an error-reporting system for PDL data, to which I would be happy to be redirected.

**Comment by helmadik** [comment]
hi! I would welcome very much any corrections you have for Lewis and Short. I run the Logeion website and we fairly regularly update our version - I see that indeed, our rice entry is not in order either! On Logeion, you'll find a link to report problems. Peter Heslin can distribute/is distributing our version.  Thanks in advance! Helma Dik.

**Comment by pjheslin** [comment]
Please do send any such corrections to Helma.  Diogenes uses her revised version of the Perseus LSJ, so the corrections will flow back there.  I should put a note on the Diogenes webpage to indicate this.

**Comment by pjheslin** [comment]
I've added a link in the Diogenes FAQs to Helma's repo for reporting errors.
