### ISSUE TITLE
Reading database locations from environment variables

### ISSUE THREAD

**Issue by daphniz** [pjheslin/diogenes#55]
It may be a good idea to let diogenes-cli read database
locations from environment variables (or something).  Adding it as an argument every time is a bit cumbersome.  Or perhaps there's another way I've overlooked?

**Comment by daphniz** [comment]
Thanks.  What's the format of `diogenes.config`?  Does it work for `xml-export.pl` as well?  I'm trying to use this on a host I don't have root on, ie. without installing.

**Comment by daphniz** [comment]
PS.  I suppose one is supposed to use the GUI programmes and set the locations there, but perhaps making `~/.local/share/tlg` &c. the default, and looking in `/usr/share/tlg` &c. if those didn't exist would be good.

**Comment by pjheslin** [comment]
For the three databases, the lines in the config file should read:

tlg_dir "/path/to/tlg/"
phi_dir "/path/to/phi/"
ddp_dir "/path/to/ddp/"

That will work for xml-export.pl, which does not have the facility to set the paths to the databases on the command-line.

If I were to supply a default path for each of the three databases, it would have to be a different default for each of the three platforms on which Diogenes runs, so with 9 defaults it's a bit complicated.

You don't need to have root to install the GUI on Linux.  You can't use the .deb or .rpm packages, but it should be straightforward to install by hand.  Download the arch package and unpack it. Change to the newly created usr/local/diogenes/ subdirectory of your current dir and run the diogenes executable.  I haven't tested this, but it should work on any modern Linux box.
