### ISSUE TITLE
authtab.xml is overwritten when exporting xml to same folder

### ISSUE THREAD

**Issue by techvslife** [pjheslin/diogenes#57]
When using the XML export function in Diogenes, the authtab.xml index file is completely overwritten. That means that the information on previously exported authors and their works is lost (assuming the same folder was used for all XML exports).   (The text themselves are not overwritten.)  

I don't see a way of re-creating only the authtab.xml file, but that also would be useful.
Thank you (--and thank you for an excellent and extremely useful program).

**Comment by techvslife** [comment]
The authtab.xml file was an unexpected bonus for me, just gravy! so of course that's fine. I can always save and later manually add together the separately generated authtab.xml files. 

The export functionality is extremely useful: getting rid of tlg hyphenated words, converting beta code to unicode, and finally having an easily, sanely parse-able file (by Python and other script languages). The authtab.xml file is important as part of navigating the XML files and easily finding what one is looking for (author AND work). Authtab.xml is also good for easily knowing what the reference numbers are (bekker versus book & chapter versus poetry line numbers etc).

As a feature suggestion, would be good if export were available for Perseus files (I don't know at all how to use "user-defined corpora" option there). (The downloadable available from Perseus are in betacode, and would be good to be put in utf-8 format and xml. But maybe Perseus will finally release those in Unicode.)  Most people now may be using Perseus texts (at least once they're pointed in the right direction), since TLG no longer makes their texts available offline (as a CD), except to the happy few who have borrowing privileges at a handful of grandfathered select libraries.

Also as another feature suggestion, would be good to have the website search feature for TEI texts available in the desktop version.  

(--But of course, that's only if it's worthwhile for you to do, and I don't know if that's an easy or hard thing.)

**Comment by pjheslin** [comment]
I think a good idea would be to embed the information about citation levels and so forth in the header of the XML files themselves rather than in an external file. I'll add that as a to-do. 

I think the Perseus files of Greek texts that are available on their Github have all been converted from Beta code to Unicode and are already in XML.  Those are the files used by DiogenesWeb.

**Comment by techvslife** [comment]
Thank you, that would be good.  

Another feature that would be very helpful to have would be a way to export search results to a database-friendly csv or simple xml format. I believe the current output format is (presentation-oriented) html or pdf. 

One can't search Perseus Unicode Greek files (or other non-TLG tei files) from Diogenes. I realize that there is work on a **web-only** Perseus replacement viewer and search utility:
https://scaife.perseus.org/
but frankly it looks like that will be _much_ less convenient for heavy, daily use (and also slower) than Diogenes desktop searches. I've looked into other options for browsing and searching TEI texts, but they're overkill and not user-friendly (--for example: though good, PhiloLogic requires setting up an Apache webserver on Linux). 

Just to give the link here for others, all Perseus texts are available in Unicode at:  https://github.com/PerseusDL/canonical-greekLit
The json file "canonical-greekLit.tracking.json"
contains the index.

Thank you again for considering these suggestions. Diogenes is a fantastic tool!

**Comment by techvslife** [comment]
I think I'll actually withdraw the suggestion on searching non-TLG/PHI, since Perseus makes available only a very limited subset for download (the "open source" library is small). (However, if that changes, or if there are other sources of downloadable Greek texts, then it would be applicable.)

**Comment by pjheslin** [comment]
If you want to import Diogenes search results into a database, the easiest way to do that would be to take the plain-text output of the command-line tool and write a script to parse it into the format you need.

If you don't like the Scaife viewer, you should try DiogenesWeb, which offers a different interface to the same texts (Perseus, First1KGreek and others, including the XML files exportd by the Diogenes desktop application).  I have not yet implemented search functionality in DiogenesWeb, but I plan to.

**Comment by techvslife** [comment]
Thank you! I haven’t used the command line tool yet, but will turn to that next.  

(btw, tlg online has a button to save search results to csv files. One can use that with their free but abridged subset (a pretty good subset!). But imo it’s *a lot* more pleasant and productive working with Diogenes than the tlg online interface, and tlg does not allow downloading of whole texts, and charges subscription fees if one wants to access more than the abridged subset.)

As far as the Diogenes web interface, I myself definitely would make use of a search feature (to use with non-tlg/phi sources, and hopefully also in  the desktop version to use with local files).
