### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by GweltazG** [pjheslin/diogenes#59]
Hi,
When I use the back button (or the shortcut Ctrl + [ ), it leads me back to the whole home page, not the page just preceding (e.g. that on I which i typed a Simple search). So I need to press again the "Search" button, then "Simple" to come back to my previous page. It unnecessarily doubles the operations, don't you find? This problem appeared with version 4. Thanks in advance and in general for all your work! 
(And please disregard ma request if it is naive, I'm totally inexperienced in all that!)

**Comment by pjheslin** [comment]
Technically, this is not a bug; it's the way it is intended to work.  But it might be a misfeature.  You see, when you click on Simple Search or any of the other options, you do not navigate away from the home page.  It's still the same page, but with part of its content modified by Javascript. So when you click on the Back button after a search you go back to the Home page and it shows you its default state.

I can see that this might be confusing if you don't know what is happening under the bonnet.  I'll see if it's possible to catch the signal from the Back button and in those cases to show the Home page not in its default state but in its last selected state.  I'm not sure if that will work, though, so I'll have to see how it goes ...

Thanks for the feedback!

**Comment by GweltazG** [comment]
Many thanks for your answer!
