### ISSUE TITLE
Another OLD pdf issue: capital U and V

### ISSUE THREAD

**Issue by mingshey** [pjheslin/diogenes#60]
(Heavily edited)

[snip]

When I search OLD item for "ultra" it stops at "Velinus" located on the same page as "uela", and prior to the page that ends with "uelo".

[snip]

[edit again]
Perseus.pm lines 628-629:
```
    $word =~ tr/vj/ui/;
    $word =~ tr /A-Z/a-z/;
```
converts lowercase v and j into lowercase u and i, respectively and then converts Uppercase letters into corresponding lowercase letters. I think this will convert Uppercase V or J into lowercase v and j, not u and i. [snip]

[edit again]
Exchange of lines 628 and 629  and search-and-replacement of v into u in `old-bookmarks.txt` did the trick for me. There were only 6  occurrences of v and no j.

**Comment by pjheslin** [comment]
You are exactly correct in diagnosing the problem and providing the fix.  This is implemented in commit 61a5c91858b17671c586eb0e411623dcb743b263.  Thanks for fixing it!  Apologies again for my slowness in responding.
