### ISSUE TITLE
Navigation trouble

### ISSUE THREAD

**Issue by helmadik** [pjheslin/diogenes#64]
-When I'm on the start of Seneca the Elder's fragments, the forward button leads to an empty page. 
-unguentatos (a Seneca fragment in Gellius cited in L&S sv unguento) shows up as search result for Seneca, but navigation to context in Seneca does not work. 
-Val Max has sections called x(ext). I have not been able to figure out how to get to those through the 'read a passage' menu. Would like to find valid 'address' for L&S citations.

**Comment by pjheslin** [comment]
1. (Seneca's fragments) This is an issue whenever the user attempts to browse beyond the end of any file.  An error is printed to the terminal, but not to the browser.  I've been meaning to do something about this for years, but never got round to it, so thanks for the prompt.  With commit 067c312a67214ba27947666cf065ae7ccbe4fea0, Diogenes now disables the "Move Forward" button and substitutes text saying that the end of file has been reached. I'm really glad that I was able to find a simple fix for a long-standing misfeature.

2. (unguentatos) As I read this, the L&S entry reports this as a bit of Seneca quoted by Aulus Gellius: "homo, P. Scipio Afric. ap. Gell. 7, 12, 5; Sen. Fragm. ib. 12, 2, 11".  Diogenes correctly interprets this and brings you to the right passage of Gellius, where Seneca is indeed quoted.

3. (Val Max). I've fixed this with commit eb4c1907372ecc24b5ba0aa8ff330ab592906485.

Thanks for the great bug reports!

**Comment by helmadik** [comment]
Here's an image to clarify the unguentatos issue. L&S does also mention the Gellius passage, but Diogenes finds a Seneca fragment if you search for the word. However, I cannot seem to navigate to it. 
![image](https://user-images.githubusercontent.com/7517297/89353406-ea648880-d67b-11ea-9169-5ff67cf03c11.png)

**Comment by pjheslin** [comment]
Ah, sorry -- I misunderstood.  I've fixed this bug with commit add81b10d98d80297358917cb098cdae97b1abd9.  Thanks for clarifying!
