### ISSUE TITLE
Installation without package managers

### ISSUE THREAD

**Issue by qgml** [pjheslin/diogenes#67]
My Linux distro doesn't use any of the supported package managers.  How do I install manually?  Shouldn't there be a `make install` procedure?

**Comment by pjheslin** [comment]
The arch package is just a generic tarball that you can unzip at the root of your filesystem.   There are a couple of arch-specific dotfiles in the root dir that you should remove afterwards. The executable is usr/local/diogenes/diogenes.  You might want to link that manually from /usr/local/bin.  Unzipping it like that won't create desktop menu items, etc. 

What Linux distro do you use?

**Comment by qgml** [comment]
I see, thanks for clarifying.  I use Void Linux.
