### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by carvalhar** [pjheslin/diogenes#68]
Could you add a flatpak package for Diogenes?
https://flatpak.org/

**Comment by pjheslin** [comment]
I thought I had replied to this earlier, but apparently not -- apologies.  In the future, when Electron development is less rapid and provides a stable target for applications, it will make sense for apps not to distribute their own copies of Electron.  At that point, I will look into revamping the installation packages for Diogenes and will look further into Flatpak.  But at the moment it is not clear what benefit it would add.
