### ISSUE TITLE
Differences in deb files dimension

### ISSUE THREAD

**Issue by Doc73** [pjheslin/diogenes#7]
Hi, Peter!
I noticed that the _deb_ file generated by manual compilation is bigger then the file downloaded from this repo. Is something missing in your _debs_?

In this case, **pr6** is from GitHub (and similar to your **pr7**), **pr7** was compiled by me:
```
$ ls -l
totale 438024
-rw-r--r-- 1 xxx xxx 157938326 apr 13 14:57 diogenes-4.0.0pr6_amd64.deb
-rw-r--r-- 1 xxx xxx 202563182 apr 13 19:50 diogenes-4.0.0pr7_amd64.deb
```

**Comment by pjheslin** [comment]
At one point there were three different versions of the LSJ lexicon included, because I was experimenting.  There is only one in pr7, but I probably left them in prebuilt-data.  I'll rebuild prebuild-data without them.

**Comment by Doc73** [comment]
Have you choosen Logeion LSJ version by default?

**Comment by pjheslin** [comment]
Yes, the installers will come with the Logeion version by default.  It has fewer errors.

**Comment by pjheslin** [comment]
I've uploaded a new version of the prebuilt data.  If you build with this, the size should be the same as for the released installer.

**Comment by Doc73** [comment]
To not open a new bug report, I point out that `make installer-deb64` now gives this result:
```
make: ***  Nessuna regola per generare l'obiettivo "app/linux64", necessario per "install/diogenes-4.0.0pr7_amd64.deb".  Arresto.
```
:cry:

**Comment by Doc73** [comment]
Sorry, It seems that now it is compulsory to run `make linux64` before `make installer-deb64`.

**Comment by pjheslin** [comment]
Yes, that was a deliberate change.
