### ISSUE TITLE
Whenever I try to sort something by author Diogenes shows nothing

### ISSUE THREAD

**Issue by alvpercru** [pjheslin/diogenes#73]
Well, as I said in the title, every time I try to search for a text in the read section, Diogenes goes full blank and I can't look for the text I'm searching for. Does this happen to anyone else?

Some screenshots:
https://gyazo.com/642dd9df59c8a0ce129a2ffab5ff4aed
https://gyazo.com/7732949d6e136a11f9364f3eee649485
https://gyazo.com/4312b4ad3f5e5e8e8fb99001263e2330
https://gyazo.com/694b6aae69a73b6228117f7aa76dee27

**Comment by pjheslin** [comment]
It looks like Diogenes cannot access the relevant file.  You should be able to see a useful error message if you start the application from the command line.  If you're on Windows, select the start menu and type "cmd".  Select "Command Prompt".

Then, launch Diogenes by typing in the path to where it is located, something like this:
C:\Program Files\Diogenes\diogenes.exe
or it may be C:\Program Files (x86)

Then proceed until you trigger the error and see what is reported in the command window.

**Comment by alvpercru** [comment]
I've done it and it shows this:

server stderr: [Wed Apr  7 22:03:17 2021] diogenes-server.pl: Null request: Timeout

server stderr: [Wed Apr  7 22:03:31 2021] diogenes-server.pl: Null request: Timeout

server stderr: [Wed Apr  7 22:03:34 2021] diogenes-server.pl: Diogenes Error: Could not open C:\Users\alpec\OneDrive\Escritorio\Universidad - Cuarto Curso\Miscel´┐¢nea\TLG/tlg0032.idt - No such file or directory at C:/Program Files (x86)/Diogenes/server/Diogenes/Base.pm line 3246.
[Wed Apr  7 22:03:34 2021] diogenes-server.pl:  Diogenes::Base::barf(Diogenes::Browser::Stateless=HASH(0x4d5611c), "Could not open C:\\Users\\alpec\\OneDrive\\Escritorio\\Universidad"...) called at C:/Program Files (x86)/Diogenes/server/Diogenes/Base.pm line 1324
[Wed Apr  7 22:03:34 2021] diogenes-server.pl:  Diogenes::Base::parse_idt(Diogenes::Browser::Stateless=HASH(0x4d5611c), 0032) called at C:/Program Files (x86)/Diogenes/server/Diogenes/Browser.pm line 38
[Wed Apr  7 22:03:34 2021] diogenes-server.pl:  Diogenes::Browser::browse_works(Diogenes::Browser::Stateless=HASH(0x4d5611c), 0032) called at C:/Program Files (x86)/Diogenes/server/Diogenes/Script.pm line 1085
[Wed Apr  7 22:03:34 2021] diogenes-server.pl:  Diogenes::Script::__ANON__() called at C:/Program Files (x86)/Diogenes/server/Diogenes/Script.pm line 1076
[Wed Apr  7 22:03:34 2021] diogenes-server.pl:  Diogenes::Script::__ANON__() called at C:/Program Files (x86)/Diogenes/server/Diogenes/Script.pm line 2150
[Wed Apr  7 22:03:34 2021] diogenes-server.pl:  Diogenes::Script::__ANON__() called at C:/Program Files (x86)/Diogenes/server/Diogenes/Script.pm line 2164
[Wed Apr  7 22:03:34 2021] diogenes-server.pl:  Diogenes::Script::__ANON__("JumpTo=&JumpFromQuery=&JumpFromLang=&JumpFromAction=&author=0"...) called at C:\Program Files (x86)\Diogenes\server\diogenes-server.pl line 374
[Wed Apr  7 22:03:34 2021] diogenes-server.pl:  eval {...} called at C:\Program Files (x86)\Diogenes\server\diogenes-server.pl line 374
[Wed Apr  7 22:03:34 2021] diogenes-server.pl:  Diogenes_Daemon::handle_request(HTTP::Daemon::ClientConn=GLOB(0x4d735c4)) called at C:\Program Files (x86)\Diogenes\server\diogenes-server.pl line 207

server stderr: [Wed Apr  7 22:03:35 2021] diogenes-server.pl: Null request: Timeout

What can I do?

**Comment by pjheslin** [comment]
Apologies for not following up on my answer.  As @Zekepotia says, the problem is the accent in the path to the folder containing the databases.  This is a known problem and is documented in the FAQs:

> Currently, if you are using Windows, you may have to put the databases in folders without any accented or non-Latin characters in the name or in the name of any of its parent folders.

Unfortunately, I don't know how to fix this.
