### ISSUE TITLE
[4.5] Zoom In/out (menu items) no longer works in Windows 8 

### ISSUE THREAD

**Issue by Ph-We** [pjheslin/diogenes#75]
Hi! I have two PCs with Windows 8.1. Unfortunately zooming in/out stopped working in the version 4.5 on both of them. It cannot be called from the menu, however it still works when I use the shortcuts.

**Comment by pjheslin** [comment]
Thanks -- I'm aware of the problem.  I assume it's a bug in the (old) verison of the Electron browser that Diogenes is currently using. I'm planning to upgrade that this summer, and I am hopeful that will fix this bug.
