### ISSUE TITLE
Diogenes get stuck when I look up a word

### ISSUE THREAD

**Issue by Sukasaptati** [pjheslin/diogenes#78]
When I click a word in the text to look it up in the dictionary, Diogenes get stuck and take a minute or so to show the result. It only happens with Latin texts, Greek texts are all right. No such problem with the older version. New laptop, with Ryzen 5000 and 16g ram. Can you tell me how to solve it? Thank you.

**Comment by Sukasaptati** [comment]
I also use diogenes on my macbook, and there is no problem

**Comment by pjheslin** [comment]
Hmm.  I'm quite mystified by this.  Sorry I was not able to help.
