### ISSUE TITLE
Mac version flagged by “VirusBarrier Scanner” as OSX/NukeSped

### ISSUE THREAD

**Issue by cessez-le-feu** [pjheslin/diogenes#82]
Hello,

I use on my Mac computers “VirusBarrier Scanner” by Intego, a free virus scanner available in the Mac App Store. And for some reason, it flags the Mac version of Diogenes ([diogenes-mac-4.5.zip](https://github.com/pjheslin/diogenes/releases/download/4.5/diogenes-mac-4.5.zip)) as OSX/NukeSped:

![capture](https://user-images.githubusercontent.com/87081549/151702629-36980ffa-6747-439d-b769-0e51b7fe1cb2.png)

**Comment by pjheslin** [comment]
Thanks for the report!  Unfortunately, this happens with antivirus software from time to time.  I have reported the false positive to Intego.  Hopefully, they will fix it soon.

**Comment by cessez-le-feu** [comment]
Thank you for taking the time to contact the antivirus maker! It’s very much appreciated.
