### ISSUE TITLE
v.4.5 not working on Fedora KDE

### ISSUE THREAD

**Issue by nivaca** [pjheslin/diogenes#84]
When trying to run Diogenes v.4.5 on Fedora KDE, I get the following error:

```
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
server stdout: 
Starting Diogenes...

server stdout: 
Startup complete. You may now point your browser at this address:
http://127.0.0.1:8892

Old version: null; Current version: 4.5
New version number saved
Deleted stale cache
[28585:0328/142755.419207:FATAL:gpu_data_manager_impl_private.cc(892)] The display compositor is frequently crashing. Goodbye.
[1]    28585 trace trap (core dumped)  diogenes
```

These are my system details:

```
Operating System: Fedora Linux 35
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.2
Kernel Version: 5.16.16-200.fc35.x86_64 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-9700 CPU @ 3.00GHz
Memory: 31.1 GiB of RAM
Graphics Processor: NVIDIA GeForce GT 710/PCIe/SSE2
```

**Comment by jiang-qian** [comment]
I don't know about what is causing the bug on fedora, but perhaps you could try using the commandline and web interface while this is getting fixed?

Open a terminal type in
/usr/local/diogenes/server/diogenes-server.pl

(or modify the beginning to point to your diogenes installation directory)
and then in a web browser on the same machine, type in this address:
http://localhost:8888/
you should be able to use diogenes just as in an application.

I hope this helps!

**Comment by nivaca** [comment]
Hi @jiang-qian, thanks. 
In an email message @pjheslin instructed me to run the app (from the command line) with:

`diogenes --no-sandbox`

(I updated the .desktop file accordingly.)
