### ISSUE TITLE
Changing server font

### ISSUE THREAD

**Issue by josh-dillon** [pjheslin/diogenes#91]
Thank you so much for the new version!

I was wondering if there's a way to change the font used when running the app in server mode. I've made a file called user.css and put it in the user preferences folder. That works fine when I run the app normally, but the change isn't applied when I run Diogenes in server mode.

I've tried replacing GentiumPlus-I.woff and GentiumPlus-R.woff with other fonts and renaming them GentiumPlus-I.woff and GentiumPlus-R.woff, as well as fiddling with the font settings in diogenes.css, but nothing seems to work.

I somehow managed to get Diogenes 4.5a to use the same font in both app and server mode, but I can't seem to get 4.6.1 to do this.

Any tips or pointers greatly appreciated!

**Comment by josh-dillon** [comment]
Sorry – I just cleared the cache and restarted the server, and the same font is now being used!

**Comment by pjheslin** [comment]
That's good!  The cache is a big source of frustration when upgrading.  There is code in the app to remember the version number and it explicitly purges the cache when the version number changes, but you have to do that manually when using a browser.

You should be able to change the font via user.css when using a browser.  One possible complication is that the configuration directory _might_ be different when running the server without the app.  And in that case, the location in which you put user.css may change.  In those cases, you might need to have two copies of that file, one for when running the app, and the other when running the server without the app.
