### ISSUE TITLE
TLG does not work in Ubuntu

### ISSUE THREAD

**Issue by huwugp** [pjheslin/diogenes#92]
I try a lot of times and just work PHI but no TLG, the page keep white without anything

**Comment by pjheslin** [comment]
It sounds like there is an issue with Diogenes accessing your copy of the TLG.  To diagnose the problem, look at the [FAQs](https://d.iogen.es/d/faqs.html) under "Why does Diogenes crash/not work?".  Follow the instructions there for running Diogenes from the command line, and see what error is reported.  If you cannot figure out the problem from that, paste the messages here.

**Comment by pjheslin** [comment]
Closing this now - please reopen if you are still having difficulty.
