### ISSUE TITLE
Shortcut for inflections lookup broken

### ISSUE THREAD

**Issue by josh-dillon** [pjheslin/diogenes#93]
I've noticed in version 4.6.2 that pressing control-option-i on the Mac no longer brings up the inflections search, but the TLG Lexica Headwords search.

Would it be possible to restore this shortcut and assign something else to headwords?

Thanks a lot!

**Comment by pjheslin** [comment]
Sorry about that -- a sloppy mistake on my part.  Fixed by commit 0e52676fb10b50d2cfaf05f5e1a5f3a3e4c36ed8, which gives Headwords the shortcut ctrl-opt-h.
