### ISSUE TITLE
Exclamation marks replaced in PHI downloads

### ISSUE THREAD

**Issue by JanRdJ** [pjheslin/diogenes#95]
I noticed that exclamation marks in XML-downloads from the PHI corpus get replaced by a period. Thus "O tempora, o mores!" becomes "O tempora, o mores.".  I looked at downloads from Terentius and Cicero which consistently show this behaviour.
Jan de Jong

**Comment by pjheslin** [comment]
Hi Jan,

I'm sorry it has taken me so long to respond - I have had a lot of teaching this term.  You are absolutely correct.  This was a stupid bug.  In the TLG, an exclamation point indicates a missing letter (as in papyri), so I changed that to a dot.  But I forgot that in the PHI texts, and exclamation point does not have that meaning.  I have fixed this in commit 1c12ca9413644b70815d42c9f3ad2abdb3dc8447.

Thanks for the report!

Peter
