### ISSUE TITLE
Where to download the required databases?

### ISSUE THREAD

**Issue by LucianoVanDerToorn** [pjheslin/diogenes#97]
Dear,

After discovering the Diogenes tool, I downloaded the Mac variant to my laptop.

I was welcomed with a setup screen, asking for multiple databases.

I tried looking up the abbreviations to see if I could find a download page of them, but was unable to do so.

Could you point me to where I can find the downloadable files?

Perhaps this can also be added to the desktop software to help out people new to the tool.

Thank you very much!

**Comment by pjheslin** [comment]
I have tried to make it clear on the website that Diogenes does not come with the databases.  It says:

> These databases are not distributed with Diogenes and must be obtained separately.

I do not distribute the databases as the intellectual property considerations are complex, unclear and may vary from country to country.
